version: '3'

services:

  master:
    build:
      context: .
      dockerfile: ./master.Dockerfile
    working_dir: /root/playbooks
    volumes:
      - ./ansible/playbooks:/root/playbooks
      - ./ansible/hosts:/etc/ansible
      - ./ansible/templates:/etc/ansible/templates
    command: tail -f /dev/null

    
  web:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    ports:
      - 8090:80  


  db:
    build:
      context: .
      dockerfile: ./server.Dockerfile
      

