---
  # Play1 - WebServer related tasks
  - name: playbook1
    hosts: webservers
    become: yes
    vars :
      list:
        - "Nom complet = Yassine EL BAHI "
        - "Status = Etudiant"
        - "Ville = Reims"
        - "Pays = France"
     
    tasks:


    - name: latest version of all required packages installed
      yum:
        name:
          - apache2
          - nginx
          - curl
        state: latest
  
    - name: httpd state running
      service:
        name: apache2
        enabled : true
        state: started
         
    - name: nginx state stopped
      service:
        name: nginx
        enabled: true
        state: stopped   

    - name: deploy index.html.jinja2 file
      template:
        src: /etc/ansible/templates/index.html.j2
        dest : /var/www/html/index.html 

    - name: appliquer ip a
      shell:
        cmd: curl ansible-web-1
      register : output 

    
    - name: affciher variable host
      debug:
        msg : "les variables sont {{ansible_ssh_user}} et {{ansible_ssh_pass}}"  

    - name: affciher résultat ip a
      debug:
        msg : "le message est {{ output.stdout_lines }}"

    # Set myTime
    - name: Set myTime
      set_fact:
        myTime: "{{ ansible_date_time.epoch }}"

    # Show results
    - name: Result
      debug:
        msg: 
        - "- The timestamp of now: {{ myTime }}"
        - "- Convert timestamp to date: {{ '%Y-%m-%d %H:%M:%S' | strftime(myTime) }}"

  
